### ISSUE TITLE
Request: Parabox max capacity change and config option

### ISSUE THREAD

**Issue by LezChap** [Darkhax-Minecraft/Parabox#2]
Right now the Parabox's maximum required power is the Java Int Cap.  On a 10 minute loop (as set up in SF4), that equals to approximately 180k RF/t.  Sure, you have the maxReceive cap, but isn't that per face?  I know it'd require a bit of coding to be compatible with Forge's Integer implementation, but with the power creep in all the other mods, I think changing the maximum required power to a Java Long would be useful.  Along with this, a config option should be available for PackMakers to fully utilize this new increase to it's full potential, or keep it at the Java Int cap if they'd like.  It should not be "easy" to run a Parabox indefinitely.

**Comment by darkhax** [comment]
Sorry for the inconvenience but please direct issues to https://github.com/Shadows-of-Fire/Parabox/issues
