### ISSUE TITLE
Request: Parabox increment style config options

### ISSUE THREAD

**Issue by LezChap** [Darkhax-Minecraft/Parabox#3]
Right now, the parabox increments linearly.  Every loop, you need 10k more RF (or whatever it's configured to).  I think there should be a few more options...some ideas would be for each loop where it doubles the previous loop requirement, or another where it will square the previous loop requirement.  Like my previous request, this should make running longer loops a lot more difficult to accomplish.

**Comment by observeroftime02** [comment]
An exponential increase would be nice for sure...

**Comment by darkhax** [comment]
Sorry for the inconvenience, but please direct issues to https://github.com/Shadows-of-Fire/Parabox/issues
