### ISSUE TITLE
Request: if (power > targetPower) nextCycle = 0;

### ISSUE THREAD

**Issue by AlexejheroYTB** [Darkhax-Minecraft/Parabox#4]
Why should we wait 9 minutes if we managed to fill the parabox with more than enough RF in the first minute?

![](https://user-images.githubusercontent.com/32238504/56880564-f66b9e80-6a65-11e9-9062-690a1ee710a7.png)

**Comment by darkhax** [comment]
Sorry for the inconvenience, but please move your issue/suggestion to https://github.com/Shadows-of-Fire/Parabox/issues. 

To answer your question, the system was designed this way deliberately as a form of balance within Sky Factory 4.
